image: fhyx/golang:edge

stages:
  - lint
  - test

services:

  - name: fhyx/postgresql:15e
    alias: testingdb

variables:
  CGO_ENABLED: '0'
  GO111MODULE: 'on'
  GOPATH: /cache/go
  GOPRIVATE: daxv.cn,fhyx.tech,hyyl.xyz
  GOPROXY: https://goproxy.io,direct
  PGX_QUERY_DEBUG: 1
  DB_NAME: testing
  DB_USER: testing
  DB_PASS: develop
  PG_EXTENSIONS: 'btree_gin btree_gist pg_trgm zhparser'
  TZ: Hongkong
  TEST_PG_STORE_DSN: postgres://testing:develop@testingdb:5432/testing?sslmode=disable

before_script:
  # Go Environments
  - go env


lint:
  stage: lint
  services: []
  script:
    - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
    - go vet ./...  && ${GOPATH}/bin/golangci-lint run -v ./...

test-models:
  stage: test
  services: []
  script:
    - go test -v -cover ./models/comm ./models/idgen ./models/oid
  coverage: '/coverage: \d+.\d+% of statements/'

test-stores:
  stage: test
  script:
    - go test -v -cover ./stores/pgx
  coverage: '/coverage: \d+.\d+% of statements/'
